insert into tasks (description, taskGroup_id) values ('Wybrać z listy zadania, które nas dotyczą','3');
insert into tasks (description, taskGroup_id) values ('Wybrać orientacyjną datę ślubu. Pora roku, będzie miała duży wpływ na resztę przygotowań.','3');
insert into tasks (description, taskGroup_id) values ('Podjąć decyzje dotyczącą rodzaju ślubu (konkordatowy/cywilny)','3');
insert into tasks (description, taskGroup_id) values ('Zrobić przegląd miejsc na wesele','3');
insert into tasks (description, taskGroup_id) values ('Ustalić orientacyjną liczbę gości','3');
insert into tasks (description, taskGroup_id) values ('Wybrać fotografa','3');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin u fotografa','3');
insert into tasks (description, taskGroup_id) values ('Podpisać umowę z fotografem','3');
insert into tasks (description, taskGroup_id) values ('Wybrać kamerzystę','3');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin u kamerzysty','3');
insert into tasks (description, taskGroup_id) values ('Podpisać umowę z kamerzystą','3');
insert into tasks (description, taskGroup_id) values ('Potwierdzić gotowość kamerzysty przed ślubem','3');
insert into tasks (description, taskGroup_id) values ('Podjąć decyzję – zespół muzyczny czy DJ czy wodzirej','4');
insert into tasks (description, taskGroup_id) values ('Wybrać zespół','4');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin zespołu','4');
insert into tasks (description, taskGroup_id) values ('Podpisać umowę z zespołem','4');
insert into tasks (description, taskGroup_id) values ('Potwierdzić gotowość zespołu przed ślubem','4');
insert into tasks (description, taskGroup_id) values ('Wybrać DJa','4');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin u DJa','4');
insert into tasks (description, taskGroup_id) values ('Podpisać umowę z DJem','4');
insert into tasks (description, taskGroup_id) values ('Potwierdzić gotowość DJa przed ślubem','4');
insert into tasks (description, taskGroup_id) values ('Wybrać wodzireja','4');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin u wodzireja','4');
insert into tasks (description, taskGroup_id) values ('Podpisać umowę z wodzirejem','4');
insert into tasks (description, taskGroup_id) values ('Potwierdzić gotowość wodzireja przed ślubem','4');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin w Kościele ','3');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin w Urzędzie Stanu Cywilnego','3');
insert into tasks (description, taskGroup_id) values ('Sprawdzić terminy nauk przedmałżeńskich','3');
insert into tasks (description, taskGroup_id) values ('Wybrać miejsce na wesele','4');
insert into tasks (description, taskGroup_id) values ('Podpisać umowę z lokalem na wesele','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za lokal','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić za lokal','4');
insert into tasks (description, taskGroup_id) values ('Ustalić termin potwierdzenia ilości gości','4');
insert into tasks (description, taskGroup_id) values ('Wybrać salony z sukniami ślubnymi','1');
insert into tasks (description, taskGroup_id) values ('Określić kwotę do przeznaczenia na suknię','1');
insert into tasks (description, taskGroup_id) values ('Umówić się na wybór sukni w salonie','1');
insert into tasks (description, taskGroup_id) values ('Wybrać osoby towarzyszące przy wyborze sukniami','1');
insert into tasks (description, taskGroup_id) values ('Ustalić z osobami towarzyszącymi datę wizyty w salonie','1');
insert into tasks (description, taskGroup_id) values ('Wybrać suknię ślubną','1');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za suknię ślubną','1');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za suknię ślubną','1');
insert into tasks (description, taskGroup_id) values ('Przymiarka sukni ślubnej','1');
insert into tasks (description, taskGroup_id) values ('Odebrać suknię ślubną','1');
insert into tasks (description, taskGroup_id) values ('Wybrać sukienkę dla Pani Młodej','1');
insert into tasks (description, taskGroup_id) values ('Przymiarka sukienki Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za sukienkę','1');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za sukienkę','1');
insert into tasks (description, taskGroup_id) values ('Odebrać sukienkę','1');
insert into tasks (description, taskGroup_id) values ('Wybrać rodzaj stroju dla Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Wybrać salony z odpowiednim strojem dla Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Wybrać strój dla Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za strój Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za strój Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Odebrać strój Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Wybrać fryzurę Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Wybrać makijaż Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin próbnej fryzury Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Próbna fryzura Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin próbnej fryzury Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Próbna fryzura Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin układania fryzury Panny Młodej przed ślubem','1');
insert into tasks (description, taskGroup_id) values ('Wizyta Panny Młodej u stylisty fryzur ','1');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin układania fryzury Pana Młodego przed ślubem','2');
insert into tasks (description, taskGroup_id) values ('Wizyta Pana Młodego u stylisty fryzur','2');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin próbnego makijażu','1');
insert into tasks (description, taskGroup_id) values ('Próbny makijaż','1');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin makijażu przed ślubem','1');
insert into tasks (description, taskGroup_id) values ('Makijaż ślubny','1');
insert into tasks (description, taskGroup_id) values ('Wybrać świadkową','3');
insert into tasks (description, taskGroup_id) values ('Wybrać świadka','3');
insert into tasks (description, taskGroup_id) values ('Poprosić świadkową o akceptację roli','3');
insert into tasks (description, taskGroup_id) values ('Poprosić świadka o akceptację roli','3');
insert into tasks (description, taskGroup_id) values ('Poprosić o pomoc w przygotowaniach wieczoru panieńskiego','3');
insert into tasks (description, taskGroup_id) values ('Poprosić o pomoc w przygotowaniach wieczoru kawalerskiego','3');
insert into tasks (description, taskGroup_id) values ('Wybrać zaproszenia','3');
insert into tasks (description, taskGroup_id) values ('Zamówić zaproszenia','3');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za zaproszenia','3');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za zaproszenia','3');
insert into tasks (description, taskGroup_id) values ('Odebrać zaproszenia','3');
insert into tasks (description, taskGroup_id) values ('Sprawdzić poprawność zaproszeń','3');
insert into tasks (description, taskGroup_id) values ('Wybrać zawiadomienia ślubne','3');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za zawiadomienia ślubne','3');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za zawiadomienia ślubne','3');
insert into tasks (description, taskGroup_id) values ('Odebrać zawiadomienia','3');
insert into tasks (description, taskGroup_id) values ('Sprawdzić zawiadomienia','3');
insert into tasks (description, taskGroup_id) values ('Wybrać środek transportu na ślub','3');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin na transport Młodej Pary','3');
insert into tasks (description, taskGroup_id) values ('Podpisać umowę za transport Młodej Pary','3');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za transport Młodej Pary','3');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za transport Młodej Pary','3');
insert into tasks (description, taskGroup_id) values ('Wybrać przystrojenie środka transportu Młodej Pary','3');
insert into tasks (description, taskGroup_id) values ('Kupić przystrojenie środka transportu Młodej Pary','3');
insert into tasks (description, taskGroup_id) values ('Przystroić transport środka transportu Młodej Pary','3');
insert into tasks (description, taskGroup_id) values ('Wybrać transport gości','3');
insert into tasks (description, taskGroup_id) values ('Zarezerwować termin transportu dla gości','3');
insert into tasks (description, taskGroup_id) values ('Podpisać umowę na transport dla gości','3');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za środek transportu Młodej Pary','3');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za środek transportu Młodej Pary','3');
insert into tasks (description, taskGroup_id) values ('Wybrać buty Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Kupić buty Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Wybrać buty Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Kupić buty Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Kupić bieliznę Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Wybrać koszulę Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Kupić koszulę Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Kupić krawat dla Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Kupić dodatki dla Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Kupić dodatki dla Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Kupić biżuterię dla Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Kupić spinki dla Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Ustalić termin potwierdzenie udziału przez gości','4');
insert into tasks (description, taskGroup_id) values ('Zaprosić gości','3');
insert into tasks (description, taskGroup_id) values ('Ustalić terminy zaproszeń osobistych','3');
insert into tasks (description, taskGroup_id) values ('Wysłać zaproszenia listowne dla gości','3');
insert into tasks (description, taskGroup_id) values ('Przypomnieć o potwierdzeniu udziału przez gości ','3');
insert into tasks (description, taskGroup_id) values ('Zarezerwować miejsca noclegowe dla gości Pani Młodej','4');
insert into tasks (description, taskGroup_id) values ('Zarezerwować miejsca noclegowe dla gości Pana Młodego','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za miejsca noclegowe dla gości Pani Młodej','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za miejsca noclegowe dla gości Pana Młodego','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za miejsca noclegowe dla gości Pani Młodej','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za miejsca noclegowe dla gości Pana Młodego','4');
insert into tasks (description, taskGroup_id) values ('Zarezerwować nocleg dla Młodej Pary','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za nocleg Młodej Pary','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za nocleg Młodej Pary','4');
insert into tasks (description, taskGroup_id) values ('Odebrać skrócony akt urodzenia Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Odebrać skrócony akt urodzenia Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Odebrać metrykę chrztu Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Odebrać metrykę chrztu Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Odebrać z USC dokumenty zezwalające na ślubnymi','3');
insert into tasks (description, taskGroup_id) values ('Złożyć dokumenty ślubne w kościele','3');
insert into tasks (description, taskGroup_id) values ('Złożyć dokumenty ślubne w USC','3');
insert into tasks (description, taskGroup_id) values ('Wybrać obrączki','3');
insert into tasks (description, taskGroup_id) values ('Zamówić obrączki','3');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za obrączki','3');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za obrączki','3');
insert into tasks (description, taskGroup_id) values ('Odebrać obrączki','3');
insert into tasks (description, taskGroup_id) values ('Zamówić tort weselny','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za tort weselnych','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za tort weselny','4');
insert into tasks (description, taskGroup_id) values ('Odebrać tort weselny','4');
insert into tasks (description, taskGroup_id) values ('Zamówić ciasta, ciasteczka…','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za ciasta, ciasteczka','4');
insert into tasks (description, taskGroup_id) values ('Odebrać ciasta, ciasteczka ','4');
insert into tasks (description, taskGroup_id) values ('Wybrać szampana na wesele','4');
insert into tasks (description, taskGroup_id) values ('Odebrać szampana na wesele','4');
insert into tasks (description, taskGroup_id) values ('Wybrać alkohole na wesele','4');
insert into tasks (description, taskGroup_id) values ('Odebrać alkohole na wesele','4');
insert into tasks (description, taskGroup_id) values ('Zaplanować podróż poślubną','4');
insert into tasks (description, taskGroup_id) values ('Ofiara na zapowiedzi przedślubne w parafii Pani Młodej','3');
insert into tasks (description, taskGroup_id) values ('Ofiara na zapowiedzi przedślubne w parafii Pana Młodego','3');
insert into tasks (description, taskGroup_id) values ('Spisanie protokołu przedślubnego w kancelarii parafialnej','3');
insert into tasks (description, taskGroup_id) values ('Zapisać się na kurs tańca','4');
insert into tasks (description, taskGroup_id) values ('Wybrać pierwszy taniec','4');
insert into tasks (description, taskGroup_id) values ('Nauczyć się pierwszego tańca','4');
insert into tasks (description, taskGroup_id) values ('Wybrać florystkę','3');
insert into tasks (description, taskGroup_id) values ('Wybrać bukiet ślubny dla Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Zamówić bukiet ślubny dla Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Odebrać bukiet ślubny dla Panny Młodej','1');
insert into tasks (description, taskGroup_id) values ('Wybrać kwiaty do butonierki dla Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Zamówić kwiaty do butonierki dla Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Odebrać kwiaty do butonierki dla Pana Młodego','2');
insert into tasks (description, taskGroup_id) values ('Wybrać dekoracje kwiatowe do kościoła','3');
insert into tasks (description, taskGroup_id) values ('Zamówić dekoracje kwiatowe do kościoła','3');
insert into tasks (description, taskGroup_id) values ('Odebrać dekoracje kwiatowe do kościoła','3');
insert into tasks (description, taskGroup_id) values ('Przybrać kościół','3');
insert into tasks (description, taskGroup_id) values ('Wybrać dekoracje kwiatowe do sali weselnej','4');
insert into tasks (description, taskGroup_id) values ('Zamówić dekoracje kwiatowe do sali weselnej','4');
insert into tasks (description, taskGroup_id) values ('Odebrać dekoracje kwiatowe do sali weselnej','4');
insert into tasks (description, taskGroup_id) values ('Ustalić dekorację sali','4');
insert into tasks (description, taskGroup_id) values ('Zamówić dekorację sali','4');
insert into tasks (description, taskGroup_id) values ('Odebrać dekorację sali','4');
insert into tasks (description, taskGroup_id) values ('Przystroić salę','4');
insert into tasks (description, taskGroup_id) values ('Ustalić ostateczną, potwierdzoną liczbę gości','4');
insert into tasks (description, taskGroup_id) values ('Ustalić rodzaj, ustawienie i nakrycie stołów','4');
insert into tasks (description, taskGroup_id) values ('Ustalić termin dostarczenia alkoholu do sali','4');
insert into tasks (description, taskGroup_id) values ('Ustalić termin dostarczenia ozdób do dekoracji sali','4');
insert into tasks (description, taskGroup_id) values ('Rozplanować usadzenie gości','4');
insert into tasks (description, taskGroup_id) values ('Ustalić menu weselne','4');
insert into tasks (description, taskGroup_id) values ('Wybrać wizytówki i winietki na stoły','4');
insert into tasks (description, taskGroup_id) values ('Zamówić wizytówki i winietki na stoły','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić zaliczkę za wizytówki i winietki','4');
insert into tasks (description, taskGroup_id) values ('Zapłacić resztę za wizytówki i winietki','4');
insert into tasks (description, taskGroup_id) values ('Odebrać wizytówki i winietki','4');
insert into tasks (description, taskGroup_id) values ('Sprawdzić wizytówki i winietki','4');
insert into tasks (description, taskGroup_id) values ('Zamówić księgę gości','4');
insert into tasks (description, taskGroup_id) values ('Zapewnić długopisy do księgi gości ','4');
insert into tasks (description, taskGroup_id) values ('Umówić wizytę u notariusza do spisania intercyzy','3');
insert into tasks (description, taskGroup_id) values ('Spisać intercyzę','3');
insert into tasks (description, taskGroup_id) values ('Omówić z księdzem przebieg mszy','3');
insert into tasks (description, taskGroup_id) values ('Ustalić osoby pomocne przy mszy (czytania, psalmy, etc.)','3');
insert into tasks (description, taskGroup_id) values ('Zaprosić osoby pomocne do pełnienia zaszczytów','3');
insert into tasks (description, taskGroup_id) values ('Przygotować podziękowanie dla rodziców','3');
insert into tasks (description, taskGroup_id) values ('Wybrać kwiaty/prezenty na pamiątkę dla rodziców','3');
insert into tasks (description, taskGroup_id) values ('Zamówić kwiaty prezenty na pamiątkę dla rodziców','3');
insert into tasks (description, taskGroup_id) values ('Odebrać kwiaty prezenty na pamiątkę dla rodziców','3');
insert into tasks (description, taskGroup_id) values ('Rozchodzić obuwie ślubne i weselne','3');
insert into tasks (description, taskGroup_id) values ('Potwierdzić obecność świadkowej','3');
insert into tasks (description, taskGroup_id) values ('Potwierdzić obecność świadka','3');
insert into tasks (description, taskGroup_id) values ('Odprężyć się','3');
insert into tasks (description, taskGroup_id) values ('Przygotować obrączki','3');
insert into tasks (description, taskGroup_id) values ('Przygotować dokumenty potrzebne do ślubu','3');
insert into tasks (description, taskGroup_id) values ('Przygotować kosmetyki, perfumy, chusteczki, dodatkowe pończochy','3');
insert into tasks (description, taskGroup_id) values ('Wziąć na ślub gotówkę, aby zapłacić usługodawcom w odliczonych kwotach','4');
