insert into tasks (description) values ('Wybrać z listy zadania, które nas dotyczą');
insert into tasks (description) values ('Wybrać orientacyjną datę ślubu. Pora roku, będzie miała duży wpływ na resztę przygotowań.');
insert into tasks (description) values ('Podjąć decyzje dotyczącą rodzaju ślubu (konkordatowy/cywilny)');
insert into tasks (description) values ('Zrobić przegląd miejsc na wesele');
insert into tasks (description) values ('Ustalić orientacyjną liczbę gości');
insert into tasks (description) values ('Wybrać fotografa');
insert into tasks (description) values ('Zarezerwować termin u fotografa');
insert into tasks (description) values ('Podpisać umowę z fotografem');
insert into tasks (description) values ('Wybrać kamerzystę');
insert into tasks (description) values ('Zarezerwować termin u kamerzysty');
insert into tasks (description) values ('Podpisać umowę z kamerzystą');
insert into tasks (description) values ('Potwierdzić gotowość kamerzysty przed ślubem');
insert into tasks (description) values ('Podjąć decyzję – zespół muzyczny czy DJ czy wodzirej');
insert into tasks (description) values ('Wybrać zespół');
insert into tasks (description) values ('Zarezerwować termin zespołu');
insert into tasks (description) values ('Podpisać umowę z zespołem');
insert into tasks (description) values ('Potwierdzić gotowość zespołu przed ślubem');
insert into tasks (description) values ('Wybrać DJ’a');
insert into tasks (description) values ('Zarezerwować termin u DJ’a');
insert into tasks (description) values ('Podpisać umowę z DJ’em');
insert into tasks (description) values ('Potwierdzić gotowość DJ’a przed ślubem');
insert into tasks (description) values ('Wybrać wodzireja');
insert into tasks (description) values ('Zarezerwować termin u wodzireja');
insert into tasks (description) values ('Podpisać umowę z wodzirejem');
insert into tasks (description) values ('Potwierdzić gotowość wodzireja przed ślubem');
insert into tasks (description) values ('Zarezerwować termin w Kościele ');
insert into tasks (description) values ('Zarezerwować termin w Urzędzie Stanu Cywilnego');
insert into tasks (description) values ('Sprawdzić terminy nauk przedmałżeńskich');
insert into tasks (description) values ('Wybrać miejsce na wesele');
insert into tasks (description) values ('Podpisać umowę z lokalem na wesele');
insert into tasks (description) values ('Zapłacić zaliczkę za lokal');
insert into tasks (description) values ('Zapłacić za lokal');
insert into tasks (description) values ('Ustalić termin potwierdzenia ilości gości');
insert into tasks (description) values ('Wybrać salony z sukniami ślubnymi');
insert into tasks (description) values ('Określić kwotę do przeznaczenia na suknię');
insert into tasks (description) values ('Umówić się na wybór sukni w salonie');
insert into tasks (description) values ('Wybrać osoby towarzyszące przy wyborze sukniami');
insert into tasks (description) values ('Ustalić z osobami towarzyszącymi datę wizyty w salonie');
insert into tasks (description) values ('Wybrać suknię ślubną');
insert into tasks (description) values ('Zapłacić zaliczkę za suknię ślubną');
insert into tasks (description) values ('Zapłacić resztę za suknię ślubną');
insert into tasks (description) values ('Przymiarka sukni ślubnej');
insert into tasks (description) values ('Odebrać suknię ślubną');
insert into tasks (description) values ('Wybrać sukienkę dla Pani Młodej');
insert into tasks (description) values ('Przymiarka sukienki Panny Młodej');
insert into tasks (description) values ('Zapłacić zaliczkę za sukienkę');
insert into tasks (description) values ('Zapłacić resztę za sukienkę');
insert into tasks (description) values ('Odebrać sukienkę');
insert into tasks (description) values ('Wybrać rodzaj stroju dla Pana Młodego');
insert into tasks (description) values ('Wybrać salony z odpowiednim strojem dla Pana Młodego');
insert into tasks (description) values ('Wybrać strój dla Pana Młodego');
insert into tasks (description) values ('Zapłacić zaliczkę za strój Pana Młodego');
insert into tasks (description) values ('Zapłacić resztę za strój Pana Młodego');
insert into tasks (description) values ('Odebrać strój Pana Młodego');
insert into tasks (description) values ('Wybrać fryzurę Panny Młodej');
insert into tasks (description) values ('Wybrać makijaż Panny Młodej');
insert into tasks (description) values ('Zarezerwować termin próbnej fryzury Panny Młodej');
insert into tasks (description) values ('Próbna fryzura Panny Młodej');
insert into tasks (description) values ('Zarezerwować termin próbnej fryzury Pana Młodego');
insert into tasks (description) values ('Próbna fryzura Pana Młodego');
insert into tasks (description) values ('Zarezerwować termin układania fryzury Panny Młodej przed ślubem');
insert into tasks (description) values ('Wizyta Panny Młodej u stylisty fryzur ');
insert into tasks (description) values ('Zarezerwować termin układania fryzury Pana Młodego przed ślubem');
insert into tasks (description) values ('Wizyta Pana Młodego u stylisty fryzur');
insert into tasks (description) values ('Zarezerwować termin próbnego makijażu');
insert into tasks (description) values ('Próbny makijaż');
insert into tasks (description) values ('Zarezerwować termin makijażu przed ślubem');
insert into tasks (description) values ('Makijaż ślubny');
insert into tasks (description) values ('Wybrać świadkową');
insert into tasks (description) values ('Wybrać świadka');
insert into tasks (description) values ('Poprosić świadkową o akceptację roli');
insert into tasks (description) values ('Poprosić świadka o akceptację roli');
insert into tasks (description) values ('Poprosić o pomoc w przygotowaniach wieczoru panieńskiego');
insert into tasks (description) values ('Poprosić o pomoc w przygotowaniach wieczoru kawalerskiego');
insert into tasks (description) values ('Wybrać zaproszenia');
insert into tasks (description) values ('Zamówić zaproszenia');
insert into tasks (description) values ('Zapłacić zaliczkę za zaproszenia');
insert into tasks (description) values ('Zapłacić resztę za zaproszenia');
insert into tasks (description) values ('Odebrać zaproszenia');
insert into tasks (description) values ('Sprawdzić poprawność zaproszeń');
insert into tasks (description) values ('Wybrać zawiadomienia ślubne');
insert into tasks (description) values ('Zapłacić zaliczkę za zawiadomienia ślubne');
insert into tasks (description) values ('Zapłacić resztę za zawiadomienia ślubne');
insert into tasks (description) values ('Odebrać zawiadomienia');
insert into tasks (description) values ('Sprawdzić zawiadomienia');
insert into tasks (description) values ('Wybrać środek transportu na ślub');
insert into tasks (description) values ('Zarezerwować termin na transport Młodej Pary');
insert into tasks (description) values ('Podpisać umowę za transport Młodej Pary');
insert into tasks (description) values ('Zapłacić zaliczkę za transport Młodej Pary');
insert into tasks (description) values ('Zapłacić resztę za transport Młodej Pary');
insert into tasks (description) values ('Wybrać przystrojenie środka transportu Młodej Pary');
insert into tasks (description) values ('Kupić przystrojenie środka transportu Młodej Pary');
insert into tasks (description) values ('Przystroić transport środka transportu Młodej Pary');
insert into tasks (description) values ('Wybrać transport gości');
insert into tasks (description) values ('Zarezerwować termin transportu dla gości');
insert into tasks (description) values ('Podpisać umowę na transport dla gości');
insert into tasks (description) values ('Zapłacić zaliczkę za środek transportu Młodej Pary');
insert into tasks (description) values ('Zapłacić resztę za środek transportu Młodej Pary');
insert into tasks (description) values ('Wybrać buty Panny Młodej');
insert into tasks (description) values ('Kupić buty Panny Młodej');
insert into tasks (description) values ('Wybrać buty Pana Młodego');
insert into tasks (description) values ('Kupić buty Pana Młodego');
insert into tasks (description) values ('Kupić bieliznę Panny Młodej');
insert into tasks (description) values ('Wybrać koszulę Pana Młodego');
insert into tasks (description) values ('Kupić koszulę Pana Młodego');
insert into tasks (description) values ('Kupić krawat dla Pana Młodego');
insert into tasks (description) values ('Kupić dodatki dla Pani Młodej');
insert into tasks (description) values ('Kupić dodatki dla Pana Młodego');
insert into tasks (description) values ('Kupić biżuterię dla Panny Młodej');
insert into tasks (description) values ('Kupić spinki dla Pana Młodego');
insert into tasks (description) values ('Ustalić termin potwierdzenie udziału przez gości');
insert into tasks (description) values ('Zaprosić gości');
insert into tasks (description) values ('Ustalić terminy zaproszeń osobistych');
insert into tasks (description) values ('Wysłać zaproszenia listowne dla gości');
insert into tasks (description) values ('Przypomnieć o potwierdzeniu udziału przez gości ');
insert into tasks (description) values ('Zarezerwować miejsca noclegowe dla gości Pani Młodej');
insert into tasks (description) values ('Zarezerwować miejsca noclegowe dla gości Pana Młodego');
insert into tasks (description) values ('Zapłacić zaliczkę za miejsca noclegowe dla gości Pani Młodej');
insert into tasks (description) values ('Zapłacić zaliczkę za miejsca noclegowe dla gości Pana Młodego');
insert into tasks (description) values ('Zapłacić resztę za miejsca noclegowe dla gości Pani Młodej');
insert into tasks (description) values ('Zapłacić resztę za miejsca noclegowe dla gości Pana Młodego');
insert into tasks (description) values ('Zarezerwować nocleg dla Młodej Pary');
insert into tasks (description) values ('Zapłacić zaliczkę za nocleg Młodej Pary');
insert into tasks (description) values ('Zapłacić resztę za nocleg Młodej Pary');
insert into tasks (description) values ('Odebrać skrócony akt urodzenia Panny Młodej');
insert into tasks (description) values ('Odebrać skrócony akt urodzenia Pana Młodego');
insert into tasks (description) values ('Odebrać metrykę chrztu Panny Młodej');
insert into tasks (description) values ('Odebrać metrykę chrztu Pana Młodego');
insert into tasks (description) values ('Odebrać z USC dokumenty zezwalające na ślubnymi');
insert into tasks (description) values ('Złożyć dokumenty ślubne w kościele');
insert into tasks (description) values ('Złożyć dokumenty ślubne w USC');
insert into tasks (description) values ('Wybrać obrączki');
insert into tasks (description) values ('Zamówić obrączki');
insert into tasks (description) values ('Zapłacić zaliczkę za obrączki');
insert into tasks (description) values ('Zapłacić resztę za obrączki');
insert into tasks (description) values ('Odebrać obrączki');
insert into tasks (description) values ('Zamówić tort weselny');
insert into tasks (description) values ('Zapłacić zaliczkę za tort weselnych');
insert into tasks (description) values ('Zapłacić resztę za tort weselny');
insert into tasks (description) values ('Odebrać tort weselny');
insert into tasks (description) values ('Zamówić ciasta, ciasteczka…');
insert into tasks (description) values ('Zapłacić zaliczkę za ciasta, ciasteczka');
insert into tasks (description) values ('Odebrać ciasta, ciasteczka ');
insert into tasks (description) values ('Wybrać szampana na wesele');
insert into tasks (description) values ('Odebrać szampana na wesele');
insert into tasks (description) values ('Wybrać alkohole na wesele');
insert into tasks (description) values ('Odebrać alkohole na wesele');
insert into tasks (description) values ('Zaplanować podróż poślubną');
insert into tasks (description) values ('Ofiara na zapowiedzi przedślubne w parafii Pani Młodej');
insert into tasks (description) values ('Ofiara na zapowiedzi przedślubne w parafii Pana Młodego');
insert into tasks (description) values ('Spisanie protokołu przedślubnego w kancelarii parafialnej');
insert into tasks (description) values ('Zapisać się na kurs tańca');
insert into tasks (description) values ('Wybrać pierwszy taniec');
insert into tasks (description) values ('Nauczyć się pierwszego tańca');
insert into tasks (description) values ('Wybrać florystkę');
insert into tasks (description) values ('Wybrać bukiet ślubny dla Panny Młodej');
insert into tasks (description) values ('Zamówić bukiet ślubny dla Panny Młodej');
insert into tasks (description) values ('Odebrać bukiet ślubny dla Panny Młodej');
insert into tasks (description) values ('Wybrać kwiaty do butonierki dla Pana Młodego');
insert into tasks (description) values ('Zamówić kwiaty do butonierki dla Pana Młodego');
insert into tasks (description) values ('Odebrać kwiaty do butonierki dla Pana Młodego');
insert into tasks (description) values ('Wybrać dekoracje kwiatowe do kościoła');
insert into tasks (description) values ('Zamówić dekoracje kwiatowe do kościoła');
insert into tasks (description) values ('Odebrać dekoracje kwiatowe do kościoła');
insert into tasks (description) values ('Przybrać kościół');
insert into tasks (description) values ('Wybrać dekoracje kwiatowe do sali weselnej');
insert into tasks (description) values ('Zamówić dekoracje kwiatowe do sali weselnej');
insert into tasks (description) values ('Odebrać dekoracje kwiatowe do sali weselnej');
insert into tasks (description) values ('Ustalić dekorację sali');
insert into tasks (description) values ('Zamówić dekorację sali');
insert into tasks (description) values ('Odebrać dekorację sali');
insert into tasks (description) values ('Przystroić salę');
insert into tasks (description) values ('Ustalić ostateczną, potwierdzoną liczbę gości');
insert into tasks (description) values ('Ustalić rodzaj, ustawienie i nakrycie stołów');
insert into tasks (description) values ('Ustalić termin dostarczenia alkoholu do sali');
insert into tasks (description) values ('Ustalić termin dostarczenia ozdób do dekoracji sali');
insert into tasks (description) values ('Rozplanować usadzenie gości');
insert into tasks (description) values ('Ustalić menu weselne');
insert into tasks (description) values ('Wybrać wizytówki i winietki na stoły');
insert into tasks (description) values ('Zamówić wizytówki i winietki na stoły');
insert into tasks (description) values ('Zapłacić zaliczkę za wizytówki i winietki');
insert into tasks (description) values ('Zapłacić resztę za wizytówki i winietki');
insert into tasks (description) values ('Odebrać wizytówki i winietki');
insert into tasks (description) values ('Sprawdzić wizytówki i winietki');
insert into tasks (description) values ('Zamówić księgę gości');
insert into tasks (description) values ('Zapewnić długopisy do księgi gości ');
insert into tasks (description) values ('Umówić wizytę u notariusza do spisania intercyzy');
insert into tasks (description) values ('Spisać intercyzę');
insert into tasks (description) values ('Omówić z księdzem przebieg mszy');
insert into tasks (description) values ('Ustalić osoby pomocne przy mszy (czytania, psalmy, etc.)');
insert into tasks (description) values ('Zaprosić osoby pomocne do pełnienia zaszczytów');
insert into tasks (description) values ('Przygotować podziękowanie dla rodziców');
insert into tasks (description) values ('Wybrać kwiaty/prezenty na pamiątkę dla rodziców');
insert into tasks (description) values ('Zamówić kwiaty prezenty na pamiątkę dla rodziców');
insert into tasks (description) values ('Odebrać kwiaty prezenty na pamiątkę dla rodziców');
insert into tasks (description) values ('Rozchodzić obuwie ślubne i weselne');
insert into tasks (description) values ('Potwierdzić obecność świadkowej');
insert into tasks (description) values ('Potwierdzić obecność świadka');
insert into tasks (description) values ('Odprężyć się');
insert into tasks (description) values ('Przygotować obrączki');
insert into tasks (description) values ('Przygotować dokumenty potrzebne do ślubu');
insert into tasks (description) values ('Przygotować kosmetyki, perfumy, chusteczki, dodatkowe pończochy');
insert into tasks (description) values ('Wziąć na ślub gotówkę, aby zapłacić usługodawcom w odliczonych kwotach');